export const SOURCE_KEYS: Record<string, string> = {
  "fit-tolerances": "passingen",
  "iso-2768": "iso2768",
  keyways: "spiebaan",
  "bearing-fits": "lager",
  "seeger-grooves": "seeger",
  fasteners: "bevestigers",
  "o-ring-grooves": "oring",
  edges: "kanten",
  units: "eenheden",
  "motor-specification": "motor",
  "pneumatic-cylinder": "cilinder",
  buckling: "knik",
  "beam-deflection": "doorbuiging",
  "cad-resources": "bronnen",
  macros: "macros",
};
